CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS exercises (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  tracking_type TEXT NOT NULL CHECK (tracking_type IN ('rep_based', 'duration_based')),
  equipment TEXT NOT NULL,
  default_metrics JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_custom BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO exercises (name, category, tracking_type, equipment, default_metrics, is_custom)
VALUES
  ('Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Incline Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Incline Bench', '["sets", "reps", "weight_kg"]', false),
  ('Decline Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Decline Bench', '["sets", "reps", "weight_kg"]', false),
  ('Dumbbell Bench Press', 'Chest', 'rep_based', 'Dumbbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Incline Dumbbell Bench Press', 'Chest', 'rep_based', 'Dumbbell, Incline Bench', '["sets", "reps", "weight_kg"]', false),
  ('Decline Dumbbell Bench Press', 'Chest', 'rep_based', 'Dumbbell, Decline Bench', '["sets", "reps", "weight_kg"]', false),
  ('Dumbbell Flyes', 'Chest', 'rep_based', 'Dumbbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Incline Dumbbell Flyes', 'Chest', 'rep_based', 'Dumbbell, Incline Bench', '["sets", "reps", "weight_kg"]', false),
  ('Cable Crossover', 'Chest', 'rep_based', 'Cable Machine', '["sets", "reps", "weight_kg"]', false),
  ('Chest Dip', 'Chest', 'rep_based', 'Dip Bars', '["sets", "reps", "weight_kg"]', false),
  ('Push-Up', 'Chest', 'rep_based', 'Bodyweight', '["sets", "reps", "weight_kg"]', false),
  ('Pec Deck Fly / Machine Fly', 'Chest', 'rep_based', 'Pec Deck Machine', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Deadlift', 'Back', 'rep_based', 'Barbell', '["sets", "reps", "weight_kg"]', false),
  ('Sumo Deadlift', 'Back', 'rep_based', 'Barbell', '["sets", "reps", "weight_kg"]', false),
  ('Bent-Over Barbell Row', 'Back', 'rep_based', 'Barbell', '["sets", "reps", "weight_kg"]', false),
  ('Pendlay Row', 'Back', 'rep_based', 'Barbell', '["sets", "reps", "weight_kg"]', false),
  ('Single-Arm Dumbbell Row', 'Back', 'rep_based', 'Dumbbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Lat Pulldown', 'Back', 'rep_based', 'Lat Pulldown Machine', '["sets", "reps", "weight_kg"]', false),
  ('Wide-Grip Lat Pulldown', 'Back', 'rep_based', 'Lat Pulldown Machine', '["sets", "reps", "weight_kg"]', false),
  ('Pull-Up', 'Back', 'rep_based', 'Pull-Up Bar', '["sets", "reps", "weight_kg"]', false),
  ('Chin-Up', 'Back', 'rep_based', 'Pull-Up Bar', '["sets", "reps", "weight_kg"]', false),
  ('Seated Cable Row', 'Back', 'rep_based', 'Cable Machine', '["sets", "reps", "weight_kg"]', false),
  ('T-Bar Row', 'Back', 'rep_based', 'T-Bar Row Machine', '["sets", "reps", "weight_kg"]', false),
  ('Hyperextension / Back Extension', 'Back', 'rep_based', 'Hyperextension Bench', '["sets", "reps", "weight_kg"]', false),
  ('Face Pull', 'Back', 'rep_based', 'Cable Machine', '["sets", "reps", "weight_kg"]', false),
  ('Overhead Barbell Press / Military Press', 'Shoulders', 'rep_based', 'Barbell', '["sets", "reps", "weight_kg"]', false),
  ('Seated Dumbbell Shoulder Press', 'Shoulders', 'rep_based', 'Dumbbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Arnold Press', 'Shoulders', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Dumbbell Lateral Raise', 'Shoulders', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Cable Lateral Raise', 'Shoulders', 'rep_based', 'Cable Machine', '["sets", "reps", "weight_kg"]', false),
  ('Dumbbell Front Raise', 'Shoulders', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Rear Delt Fly / Reverse Pec Deck', 'Shoulders', 'rep_based', 'Rear Delt Machine', '["sets", "reps", "weight_kg"]', false),
  ('Bent-Over Rear Delt Raise', 'Shoulders', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Shrug', 'Shoulders', 'rep_based', 'Barbell', '["sets", "reps", "weight_kg"]', false),
  ('Dumbbell Shrug', 'Shoulders', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Back Squat', 'Legs', 'rep_based', 'Barbell', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Front Squat', 'Legs', 'rep_based', 'Barbell', '["sets", "reps", "weight_kg"]', false),
  ('Goblet Squat', 'Legs', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Leg Press', 'Legs', 'rep_based', 'Leg Press Machine', '["sets", "reps", "weight_kg"]', false),
  ('Bulgarian Split Squat', 'Legs', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Dumbbell Walking Lunge', 'Legs', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Lunge', 'Legs', 'rep_based', 'Barbell', '["sets", "reps", "weight_kg"]', false),
  ('Leg Extension', 'Legs', 'rep_based', 'Leg Extension Machine', '["sets", "reps", "weight_kg"]', false),
  ('Hack Squat', 'Legs', 'rep_based', 'Hack Squat Machine', '["sets", "reps", "weight_kg"]', false),
  ('Hip Thrust', 'Legs', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Romanian Deadlift / RDL', 'Legs', 'rep_based', 'Barbell, Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Stiff-Legged Deadlift', 'Legs', 'rep_based', 'Barbell', '["sets", "reps", "weight_kg"]', false),
  ('Lying Leg Curl', 'Legs', 'rep_based', 'Leg Curl Machine', '["sets", "reps", "weight_kg"]', false),
  ('Seated Leg Curl', 'Legs', 'rep_based', 'Leg Curl Machine', '["sets", "reps", "weight_kg"]', false),
  ('Standing Calf Raise', 'Legs', 'rep_based', 'Standing Calf Machine', '["sets", "reps", "weight_kg"]', false),
  ('Seated Calf Raise', 'Legs', 'rep_based', 'Seated Calf Machine', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Bicep Curl', 'Biceps', 'rep_based', 'Barbell', '["sets", "reps", "weight_kg"]', false),
  ('EZ-Bar Curl', 'Biceps', 'rep_based', 'EZ Bar', '["sets", "reps", "weight_kg"]', false),
  ('Dumbbell Bicep Curl', 'Biceps', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Hammer Curl', 'Biceps', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Incline Dumbbell Curl', 'Biceps', 'rep_based', 'Dumbbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Preacher Curl', 'Biceps', 'rep_based', 'Preacher Bench, Barbell', '["sets", "reps", "weight_kg"]', false),
  ('Concentrated Curl', 'Biceps', 'rep_based', 'Dumbbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Cable Bicep Curl', 'Biceps', 'rep_based', 'Cable Machine', '["sets", "reps", "weight_kg"]', false),
  ('Close-Grip Barbell Bench Press', 'Triceps', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Triceps Dip', 'Triceps', 'rep_based', 'Dip Bars', '["sets", "reps", "weight_kg"]', false),
  ('Skull Crusher / Lying Triceps Extension', 'Triceps', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Cable Triceps Pushdown / Rope Pushdown', 'Triceps', 'rep_based', 'Cable Machine', '["sets", "reps", "weight_kg"]', false),
  ('Overhead Dumbbell Triceps Extension', 'Triceps', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Single-Arm Dumbbell Kickback', 'Triceps', 'rep_based', 'Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Ab Wheel Rollout', 'Core', 'rep_based', 'Ab Wheel', '["sets", "reps", "weight_kg"]', false),
  ('Hanging Leg Raise', 'Core', 'rep_based', 'Pull-Up Bar', '["sets", "reps", "weight_kg"]', false),
  ('Cable Crunch', 'Core', 'rep_based', 'Cable Machine', '["sets", "reps", "weight_kg"]', false),
  ('Decline Sit-Up', 'Core', 'rep_based', 'Decline Bench', '["sets", "reps", "weight_kg"]', false),
  ('Russian Twist', 'Core', 'rep_based', 'Medicine Ball', '["sets", "reps", "weight_kg"]', false),
  ('Plank', 'Core', 'duration_based', 'Bodyweight, Mat', '["duration_mmss", "weight_kg"]', false),
  ('Side Plank', 'Core', 'duration_based', 'Bodyweight, Mat', '["duration_mmss"]', false),
  ('Woodchopper / Cable Twist', 'Core', 'rep_based', 'Cable Machine', '["sets", "reps", "weight_kg"]', false),
  ('Treadmill Running', 'Cardio', 'duration_based', 'Treadmill', '["duration_mmss", "distance_km", "speed", "incline", "active_calories"]', false),
  ('Outdoor Running', 'Cardio', 'duration_based', 'Outdoor', '["duration_mmss", "distance_km", "pace", "active_calories"]', false),
  ('Stationary Cycling / Spin Bike', 'Cardio', 'duration_based', 'Spin Bike', '["duration_mmss", "distance_km", "resistance_level", "active_calories"]', false),
  ('Rowing Machine / Ergometer', 'Cardio', 'duration_based', 'Rowing Ergometer', '["duration_mmss", "distance_m", "pace_500m", "active_calories"]', false),
  ('Elliptical Trainer', 'Cardio', 'duration_based', 'Elliptical', '["duration_mmss", "distance_km", "resistance_level", "active_calories"]', false),
  ('Stairmaster / StepMill', 'Cardio', 'duration_based', 'Stairmaster', '["duration_mmss", "floors_climbed", "active_calories"]', false),
  ('Jump Rope / Skipping', 'Cardio', 'duration_based', 'Jump Rope', '["duration_mmss", "reps_jumps", "active_calories"]', false),
  ('Battle Ropes', 'Cardio', 'duration_based', 'Battle Ropes', '["sets", "duration_mmss"]', false),
  ('Kettlebell Swing', 'Cardio', 'rep_based', 'Kettlebell', '["sets", "reps", "weight_kg"]', false),
  ('Burpees', 'Cardio', 'rep_based', 'Bodyweight', '["sets", "reps"]', false),
  ('Mountain Climbers', 'Cardio', 'duration_based', 'Bodyweight, Mat', '["sets", "duration_mmss"]', false),
  ('Assault Bike / Air Bike', 'Cardio', 'duration_based', 'Assault Bike', '["duration_mmss", "active_calories"]', false),
  ('Sled Push / Prowler', 'Functional', 'duration_based', 'Prowler, Weighted Sled', '["distance_m", "weight_kg"]', false),
  ('Farmer\'s Carry', 'Functional', 'duration_based', 'Kettlebells, Dumbbells', '["distance_m", "weight_kg"]', false),
  ('Turkish Get-Up', 'Functional', 'rep_based', 'Kettlebell, Dumbbell', '["sets", "reps", "weight_kg"]', false),
  ('Box Jump', 'Functional', 'rep_based', 'Box, Plyo Box', '["sets", "reps", "height_cm"]', false),
  ('Medicine Ball Slam', 'Functional', 'rep_based', 'Medicine Ball', '["sets", "reps", "weight_kg"]', false),
  ('Wall Ball Shot', 'Functional', 'rep_based', 'Medicine Ball, Wall', '["sets", "reps", "weight_kg"]', false),
  ('Bear Crawl', 'Functional', 'duration_based', 'Bodyweight', '["distance_m"]', false),
  ('Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Incline Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false),
  ('Barbell Bench Press', 'Chest', 'rep_based', 'Barbell, Bench', '["sets", "reps", "weight_kg"]', false);

CREATE UNIQUE INDEX IF NOT EXISTS exercises_name_idx ON exercises (LOWER(name));

CREATE TABLE IF NOT EXISTS habits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'General',
  tracking_type TEXT NOT NULL DEFAULT 'boolean' CHECK (tracking_type IN ('boolean', 'numeric', 'time')),
  unit TEXT NOT NULL DEFAULT 'none',
  target_value TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
