const defaultExerciseMetrics = (trackingType = 'rep') => ({
  sets: trackingType === 'rep',
  reps: trackingType === 'rep',
  weight: trackingType === 'rep',
  duration: trackingType === 'duration',
  distance: trackingType === 'duration',
  speed: trackingType === 'duration',
  incline: false,
  pace: false,
  calories: false,
})

const exercisesSeed = [
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Barbell', 'Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'incline-dumbbell-bench-press',
    name: 'Incline Dumbbell Bench Press',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Dumbbells', 'Incline Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'pec-deck',
    name: 'Pec Deck',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Pec Deck Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'cable-crossover',
    name: 'Cable Crossover',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'incline-barbell-bench-press',
    name: 'Incline Barbell Bench Press',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Barbell', 'Incline Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Dumbbells', 'Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Dumbbells', 'Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'incline-dumbbell-fly',
    name: 'Incline Dumbbell Fly',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Dumbbells', 'Incline Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'chest-press-machine',
    name: 'Chest Press Machine',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Chest Press Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'barbell-decline-bench-press',
    name: 'Barbell Decline Bench Press',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Barbell', 'Decline Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-decline-bench-press',
    name: 'Dumbbell Decline Bench Press',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Dumbbells', 'Decline Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'push-ups',
    name: 'Push Ups',
    category: 'Chest',
    trackingType: 'rep',
    equipment: ['Bodyweight'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-bent-over-row-single-arm',
    name: 'Dumbbell Bent-Over Row (Single Arm)',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Dumbbell', 'Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'wide-grip-pulldown',
    name: 'Wide-Grip Pulldown',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Lat Pulldown Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'close-grip-pulldown',
    name: 'Close-Grip Pulldown',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Lat Pulldown Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'behind-neck-pulldown',
    name: 'Behind-Neck Pulldown',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Lat Pulldown Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'reverse-grip-pulldown',
    name: 'Reverse-Grip Pulldown',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Lat Pulldown Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'rope-pulldown',
    name: 'Rope Pulldown',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 't-bar-rows',
    name: 'T-Bar Rows',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['T-Bar Row Machine / Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'barbell-bent-over-rows-supinated-grip',
    name: 'Barbell Bent Over Rows Supinated Grip',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'pull-up',
    name: 'Pull Up',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Pull-Up Bar'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'behind-the-neck-pull-up',
    name: 'Behind the Neck Pull Up',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Pull-Up Bar'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'pull-up-supinated-grip',
    name: 'Pull Up with a Supinated Grip',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Pull-Up Bar'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'straight-arm-lat-pulldown',
    name: 'Straight Arm Lat Pulldown',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-bent-over-rows',
    name: 'Dumbbell Bent Over Rows',
    category: 'Back',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-pullover',
    name: 'Dumbbell Pullover',
    category: 'Back / Chest',
    trackingType: 'rep',
    equipment: ['Dumbbell', 'Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'barbell-pullover',
    name: 'Barbell Pullover',
    category: 'Back / Chest',
    trackingType: 'rep',
    equipment: ['Barbell', 'Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'barbell-deadlift',
    name: 'Barbell Deadlift',
    category: 'Back / Legs',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'barbell-sumo-deadlift',
    name: 'Barbell Sumo Deadlift',
    category: 'Back / Legs',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'trap-bar-deadlift',
    name: 'Trap Bar Deadlift',
    category: 'Back / Legs',
    trackingType: 'rep',
    equipment: ['Trap Bar'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-deadlift',
    name: 'Dumbbell Deadlift',
    category: 'Back / Legs',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'barbell-shrug',
    name: 'Barbell Shrug',
    category: 'Back / Shoulders',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-shrugs',
    name: 'Dumbbell Shrugs',
    category: 'Back / Shoulders',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-front-raise',
    name: 'Dumbbell Front Raise',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'high-cable-rear-delt-fly',
    name: 'High Cable Rear Delt Fly',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'smith-machine-shoulder-press',
    name: 'Smith Machine Shoulder Press',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Smith Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'barbell-upright-row',
    name: 'Barbell Upright Row',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'bent-over-lateral-raise',
    name: 'Bent-Over Lateral Raise',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'cable-one-arm-lateral-raise',
    name: 'Cable One-Arm Lateral Raise',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-push-press',
    name: 'Dumbbell Push Press',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'barbell-push-press',
    name: 'Barbell Push Press',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'single-arm-cable-front-raise',
    name: 'Single-Arm Cable Front Raise',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'barbell-front-raise',
    name: 'Barbell Front Raise',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'seated-barbell-shoulder-press',
    name: 'Seated Barbell Shoulder Press',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Barbell', 'Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'seated-behind-the-neck-barbell-shoulder-press',
    name: 'Seated Behind the Neck Barbell Shoulder Press',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Barbell', 'Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'standing-barbell-shoulder-press',
    name: 'Standing Barbell Shoulder Press',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'standing-behind-the-neck-barbell-shoulder-press',
    name: 'Standing Behind the Neck Barbell Shoulder Press',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'alternate-dumbbell-front-raise-neutral-grip',
    name: 'Alternate Dumbbell Front Raise Neutral Grip',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'one-arm-low-pulley-front-raise-neutral-grip',
    name: 'One-Arm Low-Pulley Front Raise Neutral Grip',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'two-handed-dumbbell-front-raise',
    name: 'Two-Handed Dumbbell Front Raise',
    category: 'Shoulders',
    trackingType: 'rep',
    equipment: ['Dumbbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'alternating-dumbbell-curl',
    name: 'Alternating Dumbbell Curl',
    category: 'Biceps',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'rope-cable-curl',
    name: 'Rope Cable Curl',
    category: 'Biceps',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'ez-barbell-curl',
    name: 'EZ Barbell Curl',
    category: 'Biceps',
    trackingType: 'rep',
    equipment: ['EZ Bar'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'ez-barbell-preacher-curl',
    name: 'EZ Barbell Preacher Curl',
    category: 'Biceps',
    trackingType: 'rep',
    equipment: ['EZ Bar', 'Preacher Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    category: 'Biceps',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-concentration-curl',
    name: 'Dumbbell Concentration Curl',
    category: 'Biceps',
    trackingType: 'rep',
    equipment: ['Dumbbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'single-arm-low-pulley-cable-curl',
    name: 'Single-Arm Low Pulley Cable Curl',
    category: 'Biceps',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'straight-bar-low-pulley-cable-curl',
    name: 'Straight Bar Low Pulley Cable Curl',
    category: 'Biceps',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'standing-high-pulley-cable-curl',
    name: 'Standing High Pulley Cable Curl',
    category: 'Biceps',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'seated-barbell-wrist-curl',
    name: 'Seated Barbell Wrist Curl',
    category: 'Forearms',
    trackingType: 'rep',
    equipment: ['Barbell', 'Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'seated-barbell-wrist-extension',
    name: 'Seated Barbell Wrist Extension',
    category: 'Forearms',
    trackingType: 'rep',
    equipment: ['Barbell', 'Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'reverse-barbell-curl',
    name: 'Reverse Barbell Curl',
    category: 'Forearms / Biceps',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'lying-triceps-extension',
    name: 'Lying Triceps Extension',
    category: 'Triceps',
    trackingType: 'rep',
    equipment: ['EZ Bar / Barbell', 'Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'triceps-pushdown',
    name: 'Triceps Pushdown',
    category: 'Triceps',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'rope-triceps-pushdown',
    name: 'Rope Triceps Pushdown',
    category: 'Triceps',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-triceps-extension',
    name: 'Dumbbell Triceps Extension',
    category: 'Triceps',
    trackingType: 'rep',
    equipment: ['Dumbbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'bench-dip',
    name: 'Bench Dip',
    category: 'Triceps',
    trackingType: 'rep',
    equipment: ['Bench'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'crunch',
    name: 'Crunch',
    category: 'Abdominals',
    trackingType: 'rep',
    equipment: ['Bodyweight / Mat'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'oblique-crunch',
    name: 'Oblique Crunch',
    category: 'Abdominals',
    trackingType: 'rep',
    equipment: ['Bodyweight / Mat'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'crunch-machine',
    name: 'Crunch Machine',
    category: 'Abdominals',
    trackingType: 'rep',
    equipment: ['Crunch Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'rope-ab-pulldown',
    name: 'Rope Ab Pulldown',
    category: 'Abdominals',
    trackingType: 'rep',
    equipment: ['Cable Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'Abdominals',
    trackingType: 'duration',
    equipment: ['Bodyweight / Mat'],
    metrics: defaultExerciseMetrics('duration'),
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'Abdominals',
    trackingType: 'rep',
    equipment: ['Pull-Up Bar'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'bent-knee-reverse-crunch',
    name: 'Bent Knee Reverse Crunch',
    category: 'Abdominals',
    trackingType: 'rep',
    equipment: ['Bodyweight / Mat'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'long-arm-crunch',
    name: 'Long Arm Crunch',
    category: 'Abdominals',
    trackingType: 'rep',
    equipment: ['Bodyweight / Mat'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'plank-get-ups',
    name: 'Plank Get Ups',
    category: 'Abdominals',
    trackingType: 'duration',
    equipment: ['Bodyweight / Mat'],
    metrics: defaultExerciseMetrics('duration'),
  },
  {
    id: 'squat',
    name: 'Squat',
    category: 'Legs',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    category: 'Legs',
    trackingType: 'rep',
    equipment: ['Hack Squat Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    category: 'Legs',
    trackingType: 'rep',
    equipment: ['Barbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    category: 'Legs',
    trackingType: 'duration',
    equipment: ['Bodyweight / Wall'],
    metrics: defaultExerciseMetrics('duration'),
  },
  {
    id: 'bodyweight-glute-bridge',
    name: 'Bodyweight Glute Bridge',
    category: 'Legs / Glutes',
    trackingType: 'rep',
    equipment: ['Bodyweight / Mat'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'seated-hip-abduction-machine',
    name: 'Seated Hip Abduction Machine',
    category: 'Legs / Glutes',
    trackingType: 'rep',
    equipment: ['Hip Abduction Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'Legs',
    trackingType: 'rep',
    equipment: ['Leg Press Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: 'Legs',
    trackingType: 'rep',
    equipment: ['Leg Extension Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    category: 'Legs',
    trackingType: 'rep',
    equipment: ['Leg Curl Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    category: 'Legs',
    trackingType: 'rep',
    equipment: ['Dumbbells'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'medicine-ball-deadlift',
    name: 'Medicine Ball Deadlift',
    category: 'Legs',
    trackingType: 'rep',
    equipment: ['Medicine Ball'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'single-leg-bodyweight-deadlift',
    name: 'Single Leg Bodyweight Deadlift',
    category: 'Legs',
    trackingType: 'rep',
    equipment: ['Bodyweight'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    category: 'Calves',
    trackingType: 'rep',
    equipment: ['Seated Calf Machine'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    category: 'Calves',
    trackingType: 'rep',
    equipment: ['Standing Calf Machine / Dumbbell'],
    metrics: defaultExerciseMetrics('rep'),
  },
  {
    id: 'rowing-machine',
    name: 'Rowing Machine',
    category: 'Cardio / Full Body',
    trackingType: 'duration',
    equipment: ['Rowing Ergometer'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: true, speed: false, incline: false, pace: true, calories: false },
  },
  {
    id: 'treadmill-running-walking',
    name: 'Treadmill Running / Walking',
    category: 'Cardio / Legs',
    trackingType: 'duration',
    equipment: ['Treadmill'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: true, speed: true, incline: true, pace: false, calories: false },
  },
  {
    id: 'stair-master-steppers',
    name: 'Stair Master / Steppers',
    category: 'Cardio / Legs',
    trackingType: 'duration',
    equipment: ['Stair Climber'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: false },
  },
  {
    id: 'outdoor-walking-running',
    name: 'Outdoor Walking / Running',
    category: 'Cardio / Legs',
    trackingType: 'duration',
    equipment: ['Bodyweight / Outdoor'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: true, speed: false, incline: false, pace: false, calories: false },
  },
  {
    id: 'standing-hamstring-stretch',
    name: 'Standing Hamstring Stretch',
    category: 'Flexibility / Legs',
    trackingType: 'duration',
    equipment: ['Bodyweight / Mat'],
    metrics: { sets: true, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: false },
  },
  {
    id: 'cobra-stretch',
    name: 'Cobra Stretch',
    category: 'Flexibility / Core & Back',
    trackingType: 'duration',
    equipment: ['Bodyweight / Mat'],
    metrics: { sets: true, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: false },
  },
  {
    id: 'childs-pose',
    name: 'Child\'s Pose',
    category: 'Flexibility / Back & Shoulders',
    trackingType: 'duration',
    equipment: ['Bodyweight / Mat'],
    metrics: { sets: true, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: false },
  },
  {
    id: 'quad-stretch-standing',
    name: 'Quad Stretch (Standing)',
    category: 'Flexibility / Legs',
    trackingType: 'duration',
    equipment: ['Bodyweight'],
    metrics: { sets: true, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: false },
  },
  {
    id: 'doorway-chest-stretch',
    name: 'Doorway Chest Stretch',
    category: 'Flexibility / Chest',
    trackingType: 'duration',
    equipment: ['Doorway / Wall'],
    metrics: { sets: true, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: false },
  },
  {
    id: 'cross-body-shoulder-stretch',
    name: 'Cross-Body Shoulder Stretch',
    category: 'Flexibility / Shoulders',
    trackingType: 'duration',
    equipment: ['Bodyweight'],
    metrics: { sets: true, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: false },
  },
  {
    id: 'hip-flexor-lunge-stretch',
    name: 'Hip Flexor Lunge Stretch',
    category: 'Flexibility / Hips',
    trackingType: 'duration',
    equipment: ['Bodyweight / Mat'],
    metrics: { sets: true, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: false },
  },
  {
    id: 'dynamic-warm-up-routine',
    name: 'Dynamic Warm-Up Routine',
    category: 'Flexibility / Full Body',
    trackingType: 'duration',
    equipment: ['Bodyweight'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: false },
  },
  {
    id: 'basketball',
    name: 'Basketball',
    category: 'Sports / Cardio',
    trackingType: 'duration',
    equipment: ['Basketball & Court'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: true },
  },
  {
    id: 'soccer-football',
    name: 'Soccer / Football',
    category: 'Sports / Cardio',
    trackingType: 'duration',
    equipment: ['Soccer Ball & Pitch'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: true, speed: false, incline: false, pace: false, calories: true },
  },
  {
    id: 'tennis-padel',
    name: 'Tennis / Padel',
    category: 'Sports / Agility',
    trackingType: 'duration',
    equipment: ['Racket, Ball & Court'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: true },
  },
  {
    id: 'swimming-laps',
    name: 'Swimming (Laps)',
    category: 'Sports / Full Body',
    trackingType: 'duration',
    equipment: ['Pool'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: true, speed: false, incline: false, pace: false, calories: false },
  },
  {
    id: 'cycling-road-mountain',
    name: 'Cycling (Road / Mountain)',
    category: 'Sports / Cardio',
    trackingType: 'duration',
    equipment: ['Bicycle & Helmet'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: true, speed: true, incline: false, pace: false, calories: false },
  },
  {
    id: 'volleyball',
    name: 'Volleyball',
    category: 'Sports / Agility',
    trackingType: 'duration',
    equipment: ['Volleyball & Net'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: true },
  },
  {
    id: 'badminton',
    name: 'Badminton',
    category: 'Sports / Agility',
    trackingType: 'duration',
    equipment: ['Racket, Shuttlecock & Net'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: true },
  },
  {
    id: 'martial-arts-boxing',
    name: 'Martial Arts / Boxing',
    category: 'Sports / Full Body',
    trackingType: 'duration',
    equipment: ['Gloves / Mat / Heavy Bag'],
    metrics: { sets: false, reps: false, weight: false, duration: true, distance: false, speed: false, incline: false, pace: false, calories: true },
  },
]

export default exercisesSeed
